#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative "lexer"
  require_relative "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 130)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code)
    puts @tokens.inspect if show_tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    27,    25,    26,    16,    18,    19,    20,    21,    22,    23,
    24,    27,    25,    26,    16,    18,    19,    20,    21,    22,
    23,    24,    30,    72,    41,    42,    39,    40,    15,    16,
    17,    30,    88,    41,    42,    39,    40,    46,    45,    15,
    74,    17,    27,    25,    26,    51,    18,    19,    20,    21,
    22,    23,    24,    27,    25,    26,    17,    18,    19,    20,
    21,    22,    23,    24,    30,    16,    41,    42,    39,    40,
    15,    68,    49,    30,    84,    41,    42,    48,    27,    25,
    26,    15,    18,    19,    20,    21,    22,    23,    24,    27,
    25,    26,    17,    18,    19,    20,    21,    22,    23,    24,
    78,    47,    79,    27,    25,    26,    15,    18,    19,    20,
    21,    22,    23,    24,    27,    25,    26,    15,    18,    19,
    20,    21,    22,    23,    24,    85,    72,    86,    27,    25,
    26,    15,    18,    19,    20,    21,    22,    23,    24,    27,
    25,    26,    15,    18,    19,    20,    21,    22,    23,    24,
    45,    30,    30,    27,    25,    26,    15,    18,    19,    20,
    21,    22,    23,    24,    27,    25,    26,    15,    18,    19,
    20,    21,    22,    23,    24,    82,    28,    72,    27,    25,
    26,    15,    18,    19,    20,    21,    22,    23,    24,    27,
    25,    26,    15,    18,    19,    20,    21,    22,    23,    24,
    53,   nil,   nil,    27,    25,    26,    15,    18,    19,    20,
    21,    22,    23,    24,    27,    25,    26,    15,    18,    19,
    20,    21,    22,    23,    24,   nil,   nil,   nil,    27,    25,
    26,    15,    18,    19,    20,    21,    22,    23,    24,    27,
    25,    26,    15,    18,    19,    20,    21,    22,    23,    24,
   nil,   nil,   nil,    27,    25,    26,    15,    18,    19,    20,
    21,    22,    23,    24,    27,    25,    26,    15,    18,    19,
    20,    21,    22,    23,    24,   nil,   nil,   nil,    27,    25,
    26,    15,    18,    19,    20,    21,    22,    23,    24,   nil,
   nil,    30,    15,    41,    42,    39,    40,    35,    36,    37,
    38,    33,    34,    32,    31,   nil,    15,    66,    72,   nil,
    30,   nil,    41,    42,    39,    40,    35,    36,    37,    38,
    33,    34,    32,    31,    30,   nil,    41,    42,    39,    40,
    35,    36,    37,    38,    33,    34,    32,    31,    30,   nil,
    41,    42,    39,    40,    35,    36,    37,    38,    33,    34,
    32,    31,    30,   nil,    41,    42,    39,    40,    35,    36,
    37,    38,    33,    34,    32,    31,    30,   nil,    41,    42,
    39,    40,    35,    36,    37,    38,    33,    34,    32,    31,
    30,   nil,    41,    42,    39,    40,    35,    36,    37,    38,
    33,    34,    32,    31,    30,   nil,    41,    42,    39,    40,
    35,    36,    37,    38,    33,    34,    32,    31,    30,   nil,
    41,    42,    39,    40,    35,    36,    37,    38,    33,    34,
    32,    30,   nil,    41,    42,    39,    40,    35,    36,    37,
    38,    33,    34,    30,   nil,    41,    42,    39,    40,    35,
    36,    37,    38,    30,   nil,    41,    42,    39,    40,    35,
    36,    37,    38,    30,   nil,    41,    42,    39,    40,    30,
   nil,    41,    42 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    72,    72,    72,    72,    72,    72,    72,    72,    72,
    72,    72,    58,    48,    58,    58,    58,    58,     0,     2,
     0,    59,    86,    59,    59,    59,    59,    23,    23,    72,
    48,    72,    45,    45,    45,    28,    45,    45,    45,    45,
    45,    45,    45,    40,    40,    40,     2,    40,    40,    40,
    40,    40,    40,    40,    60,    80,    60,    60,    60,    60,
    45,    45,    26,    63,    80,    63,    63,    25,    79,    79,
    79,    40,    79,    79,    79,    79,    79,    79,    79,    15,
    15,    15,    80,    15,    15,    15,    15,    15,    15,    15,
    69,    24,    69,    39,    39,    39,    79,    39,    39,    39,
    39,    39,    39,    39,    41,    41,    41,    15,    41,    41,
    41,    41,    41,    41,    41,    81,    49,    81,    47,    47,
    47,    39,    47,    47,    47,    47,    47,    47,    47,    46,
    46,    46,    41,    46,    46,    46,    46,    46,    46,    46,
    53,    64,    65,    27,    27,    27,    47,    27,    27,    27,
    27,    27,    27,    27,    29,    29,    29,    46,    29,    29,
    29,    29,    29,    29,    29,    74,     1,    85,    42,    42,
    42,    27,    42,    42,    42,    42,    42,    42,    42,    31,
    31,    31,    29,    31,    31,    31,    31,    31,    31,    31,
    30,   nil,   nil,    32,    32,    32,    42,    32,    32,    32,
    32,    32,    32,    32,    33,    33,    33,    31,    33,    33,
    33,    33,    33,    33,    33,   nil,   nil,   nil,    34,    34,
    34,    32,    34,    34,    34,    34,    34,    34,    34,    35,
    35,    35,    33,    35,    35,    35,    35,    35,    35,    35,
   nil,   nil,   nil,    36,    36,    36,    34,    36,    36,    36,
    36,    36,    36,    36,    37,    37,    37,    35,    37,    37,
    37,    37,    37,    37,    37,   nil,   nil,   nil,    38,    38,
    38,    36,    38,    38,    38,    38,    38,    38,    38,   nil,
   nil,    43,    37,    43,    43,    43,    43,    43,    43,    43,
    43,    43,    43,    43,    43,   nil,    38,    43,    50,   nil,
    50,   nil,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    70,   nil,    70,    70,    70,    70,
    70,    70,    70,    70,    70,    70,    70,    70,    71,   nil,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    71,    71,    83,   nil,    83,    83,    83,    83,    83,    83,
    83,    83,    83,    83,    83,    83,    67,   nil,    67,    67,
    67,    67,    67,    67,    67,    67,    67,    67,    67,    67,
     3,   nil,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,    52,   nil,    52,    52,    52,    52,
    52,    52,    52,    52,    52,    52,    52,    52,    54,   nil,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    55,   nil,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    55,    56,   nil,    56,    56,    56,    56,    56,
    56,    56,    56,    57,   nil,    57,    57,    57,    57,    57,
    57,    57,    57,    61,   nil,    61,    61,    61,    61,    62,
   nil,    62,    62 ]

racc_action_pointer = [
    -2,   176,    24,   365,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    87,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     8,    72,    66,    60,   151,    45,   162,
   189,   187,   201,   212,   226,   237,   251,   262,   276,   101,
    51,   112,   176,   276,   nil,    40,   137,   126,    10,   113,
   295,   nil,   379,   120,   393,   406,   418,   428,     7,    16,
    49,   438,   444,    58,   136,   137,   nil,   351,   nil,    69,
   309,   323,     9,   nil,   164,   nil,   nil,   nil,   nil,    76,
    60,    94,   nil,   337,   nil,   164,    21,   nil,   nil ]

racc_action_default = [
    -1,   -57,    -2,    -3,    -7,    -8,    -9,   -10,   -11,   -12,
   -13,   -14,   -15,   -16,   -17,   -57,   -19,   -20,   -21,   -22,
   -23,   -24,   -25,   -47,   -45,   -57,   -57,   -57,   -57,    -5,
   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,
   -57,   -57,   -57,   -57,   -26,   -57,   -57,   -57,   -57,   -57,
   -57,    89,    -4,   -28,   -33,   -34,   -35,   -36,   -37,   -38,
   -39,   -40,   -41,   -42,   -43,   -44,   -18,   -31,   -29,   -57,
   -48,   -46,   -57,   -50,   -52,   -55,   -56,   -27,   -30,   -57,
   -57,   -57,   -53,   -32,   -49,   -57,   -57,   -51,   -54 ]

racc_goto_table = [
    29,     2,    43,    73,    75,    76,    44,    81,    69,     1,
   nil,   nil,   nil,   nil,    50,   nil,    52,   nil,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
   nil,   nil,    67,    70,    71,   nil,    77,   nil,   nil,   nil,
    87,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    83,   nil,   nil,   nil,
   nil,   nil,   nil,    80,   nil,   nil,   nil,   nil,    29 ]

racc_goto_check = [
     4,     2,     3,    17,    17,    17,    15,    18,    16,     1,
   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
   nil,   nil,     3,     3,     3,   nil,    15,   nil,   nil,   nil,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,
   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     9,     1,   -13,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   -17,   -37,   -45,   -67 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 35, :_reduce_1,
  1, 35, :_reduce_2,
  1, 36, :_reduce_3,
  3, 36, :_reduce_4,
  2, 36, :_reduce_5,
  2, 36, :_reduce_6,
  1, 36, :_reduce_7,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  3, 37, :_reduce_18,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 39, :_reduce_21,
  1, 39, :_reduce_22,
  1, 39, :_reduce_23,
  1, 39, :_reduce_24,
  1, 39, :_reduce_25,
  2, 40, :_reduce_26,
  4, 40, :_reduce_27,
  3, 40, :_reduce_28,
  2, 49, :_reduce_29,
  3, 49, :_reduce_30,
  1, 50, :_reduce_31,
  3, 50, :_reduce_32,
  3, 41, :_reduce_33,
  3, 41, :_reduce_34,
  3, 41, :_reduce_35,
  3, 41, :_reduce_36,
  3, 41, :_reduce_37,
  3, 41, :_reduce_38,
  3, 41, :_reduce_39,
  3, 41, :_reduce_40,
  3, 41, :_reduce_41,
  3, 41, :_reduce_42,
  3, 41, :_reduce_43,
  3, 41, :_reduce_44,
  1, 42, :_reduce_45,
  3, 43, :_reduce_46,
  1, 44, :_reduce_47,
  3, 45, :_reduce_48,
  3, 51, :_reduce_49,
  3, 46, :_reduce_50,
  6, 46, :_reduce_51,
  0, 52, :_reduce_52,
  1, 52, :_reduce_53,
  3, 52, :_reduce_54,
  3, 47, :_reduce_55,
  3, 48, :_reduce_56 ]

racc_reduce_n = 57

racc_shift_n = 89

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :DEF => 3,
  :CLASS => 4,
  :NEWLINE => 5,
  :NUMBER => 6,
  :STRING => 7,
  :TRUE => 8,
  :FALSE => 9,
  :NIL => 10,
  :IDENTIFIER => 11,
  :CONSTANT => 12,
  :INDENT => 13,
  :DEDENT => 14,
  "." => 15,
  "!" => 16,
  "*" => 17,
  "/" => 18,
  "+" => 19,
  "-" => 20,
  ">" => 21,
  ">=" => 22,
  "<" => 23,
  "<=" => 24,
  "==" => 25,
  "!=" => 26,
  "&&" => 27,
  "||" => 28,
  "=" => 29,
  "(" => 30,
  ")" => 31,
  ";" => 32,
  "," => 33 }

racc_nt_base = 34

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "DEF",
  "CLASS",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "INDENT",
  "DEDENT",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\",\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "GetConstant",
  "SetConstant",
  "GetLocal",
  "SetLocal",
  "Def",
  "Class",
  "If",
  "Arguments",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 29)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 32)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 33)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 34)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 35)
  def _reduce_6(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 36)
  def _reduce_7(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'grammar.y', 49)
  def _reduce_18(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'grammar.y', 56)
  def _reduce_21(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 57)
  def _reduce_22(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 58)
  def _reduce_23(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 59)
  def _reduce_24(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 60)
  def _reduce_25(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 63)
  def _reduce_26(val, _values, result)
     result = CallNode.new(nil, val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 65)
  def _reduce_27(val, _values, result)
     result = CallNode.new(val[0], val[2], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 66)
  def _reduce_28(val, _values, result)
     result = CallNode.new(val[0], val[2], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 70)
  def _reduce_29(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 71)
  def _reduce_30(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 74)
  def _reduce_31(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 75)
  def _reduce_32(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 78)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 79)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 80)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 81)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 85)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 86)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 87)
  def _reduce_42(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 88)
  def _reduce_43(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 89)
  def _reduce_44(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_45(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 95)
  def _reduce_46(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 98)
  def _reduce_47(val, _values, result)
     result = GetLocalNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 101)
  def _reduce_48(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 104)
  def _reduce_49(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 107)
  def _reduce_50(val, _values, result)
     result = DefNode.new(val[1], [], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_51(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_52(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_53(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_54(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 117)
  def _reduce_55(val, _values, result)
     result = ClassNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 120)
  def _reduce_56(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
